In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit
from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fire/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Trace\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Trace\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            intensity=np.trace(cdi)
            in_list.append(intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            intensity=np.trace(cdi)
            in_list.append(intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Entropy=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Entropy)):
#     Combine_Entropy[i] = ((min_max_scaler.fit_transform(np.array(Combine_Entropy[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Entropy:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [5]:
x = [0] * 126
y =[1]*142
z=x+y
#combine_dict={'entropy':new_list,'label':z}
combine_dict1={'entropy':new_list,'label':z}
df=pd.DataFrame(combine_dict1)

display(df)

y=df['label'].values

                                               entropy  label
0    0 0 0 255 255 510 510 255 255 255 255 0 255 25...      0
1    765 0 0 0 0 510 510 510 0 255 255 0 0 0 0 0 25...      0
2    255 255 510 510 765 1530 1020 510 510 1020 102...      0
3    1020 0 1785 2295 1020 510 1020 765 765 2040 15...      0
4    1275 1275 2040 765 765 1530 2550 2550 2550 765...      0
..                                                 ...    ...
263  1785 3570 2040 3315 3570 4845 2805 2040 2295 1...      1
264  510 510 0 255 1785 765 255 0 0 0 0 0 255 510 1...      1
265  0 0 0 765 1020 765 1020 1020 1275 2295 510 178...      1
266  255 255 255 0 510 0 0 0 255 0 0 1275 255 255 2...      1
267  510 0 1020 1020 1785 510 2040 1530 255 765 153...      1

[268 rows x 2 columns]

In [6]:
data_df = df['entropy'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fire/CDI_Based/Trace/CSV/Canny.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,0,0,0,255,255,510,510,255,255,255,...,0,510,255,510,510,765,1275,255,255,0
1,765,0,0,0,0,510,510,510,0,255,...,255,255,0,255,255,255,510,0,765,0
2,255,255,510,510,765,1530,1020,510,510,1020,...,1275,510,1020,255,255,1020,765,765,510,0
3,1020,0,1785,2295,1020,510,1020,765,765,2040,...,0,0,0,0,0,0,0,0,0,0
4,1275,1275,2040,765,765,1530,2550,2550,2550,765,...,1275,1530,1530,1020,1275,1020,3315,1530,2550,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,1785,3570,2040,3315,3570,4845,2805,2040,2295,1020,...,255,0,1530,2550,2295,3570,255,765,2295,1
264,510,510,0,255,1785,765,255,0,0,0,...,1785,2040,1275,1530,1785,510,1020,1530,765,1
265,0,0,0,765,1020,765,1020,1020,1275,2295,...,510,255,255,765,255,510,765,2295,765,1
266,255,255,255,0,510,0,0,0,255,0,...,510,0,0,0,0,0,0,0,510,1
267,510,0,1020,1020,1785,510,2040,1530,255,765,...,255,1020,1020,255,255,0,255,255,255,1