In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit
from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fire/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Trace\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Trace\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(positive_os)

for i in video:
    video_name=positive_os+i
    #print(video_name)
    cap = cv.VideoCapture(video_name)
    num=cap.get(7)
    if num!=30:
        print(i)
    while 1:
        ret,frame=cap.read() 
        if ret:
            cv.imshow('frame',frame)
            k = cv.waitKey(1) 
            if k ==27:     
                break 
        else:
            break
cv.destroyAllWindows()

In [3]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            intensity=np.trace(cdi)
            in_list.append(intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            intensity=np.trace(cdi)
            in_list.append(intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [5]:

Combine_Entropy=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Entropy)):
#     Combine_Entropy[i] = ((min_max_scaler.fit_transform(np.array(Combine_Entropy[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Entropy:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [6]:
x = [0] * 126
y =[1]*142
z=x+y

In [7]:
#combine_dict={'entropy':new_list,'label':z}
combine_dict1={'entropy':new_list,'label':z}
df=pd.DataFrame(combine_dict1)

display(df)

y=df['label'].values

                                               entropy  label
0    42 33 44 35 34 14 20 18 14 24 34 58 16 17 31 2...      0
1    54 35 28 52 32 43 36 36 35 35 45 50 30 24 31 1...      0
2    229 183 155 196 187 298 111 184 176 226 295 21...      0
3    141 111 183 372 355 506 588 166 176 264 169 13...      0
4    224 314 217 188 365 386 513 580 553 391 380 49...      0
..                                                 ...    ...
263  715 512 742 611 1498 1551 845 926 2270 2740 38...      1
264  128 83 27 38 1135 221 138 170 18 15 383 583 89...      1
265  2 0 0 286 649 518 495 348 313 262 249 145 196 ...      1
266  316 344 478 481 4280 351 295 824 1710 429 454 ...      1
267  125 103 331 570 576 400 436 549 169 205 303 18...      1

[268 rows x 2 columns]

In [8]:
data_df = df['entropy'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fire/CDI_Based/Trace/CSV/Gray.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,42,33,44,35,34,14,20,18,14,24,...,43,146,264,170,214,143,192,145,204,0
1,54,35,28,52,32,43,36,36,35,35,...,64,43,42,61,70,31,20,23,27,0
2,229,183,155,196,187,298,111,184,176,226,...,180,177,233,231,272,319,174,189,242,0
3,141,111,183,372,355,506,588,166,176,264,...,0,0,0,0,1,0,0,0,0,0
4,224,314,217,188,365,386,513,580,553,391,...,214,226,352,317,197,363,499,546,442,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,715,512,742,611,1498,1551,845,926,2270,2740,...,469,185,203,432,516,469,434,326,227,1
264,128,83,27,38,1135,221,138,170,18,15,...,431,193,281,571,378,407,324,189,127,1
265,2,0,0,286,649,518,495,348,313,262,...,133,127,152,85,272,278,286,1029,911,1
266,316,344,478,481,4280,351,295,824,1710,429,...,1725,735,871,647,320,549,3307,1900,628,1
267,125,103,331,570,576,400,436,549,169,205,...,158,208,197,174,120,70,45,66,135,1