In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit
from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fire/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Trace\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Trace\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='LAPLACIAN')
            intensity=np.trace(cdi)
            in_list.append(intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='LAPLACIAN')
            intensity=np.trace(cdi)
            in_list.append(intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Entropy=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Entropy)):
#     Combine_Entropy[i] = ((min_max_scaler.fit_transform(np.array(Combine_Entropy[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Entropy:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [5]:
x = [0] * 126
y =[1]*142
z=x+y

In [6]:
#combine_dict={'entropy':new_list,'label':z}
combine_dict1={'entropy':new_list,'label':z}
df=pd.DataFrame(combine_dict1)

display(df)

y=df['label'].values

                                               entropy  label
0    96 87 84 83 70 61 29 46 43 75 80 134 39 53 63 ...      0
1    93 100 98 94 125 83 69 94 97 70 95 177 92 105 ...      0
2    404 322 283 290 241 314 171 266 248 284 260 21...      0
3    191 204 254 479 451 281 761 325 339 469 369 20...      0
4    369 162 148 156 380 285 338 474 222 313 392 29...      0
..                                                 ...    ...
263  247 338 478 366 478 361 375 250 375 171 273 16...      1
264  62 44 23 37 168 128 47 23 8 19 56 161 86 138 1...      1
265  5 0 0 145 237 174 193 229 201 216 226 145 160 ...      1
266  189 155 159 160 265 162 133 160 154 165 179 37...      1
267  82 81 396 555 322 260 468 391 175 271 380 148 ...      1

[268 rows x 2 columns]

In [7]:
data_df = df['entropy'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fire/CDI_Based/Trace/CSV/Laplacian.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,96,87,84,83,70,61,29,46,43,75,...,120,148,843,304,276,433,99,179,234,0
1,93,100,98,94,125,83,69,94,97,70,...,182,129,145,148,221,124,64,76,62,0
2,404,322,283,290,241,314,171,266,248,284,...,225,266,171,322,243,369,317,191,289,0
3,191,204,254,479,451,281,761,325,339,469,...,0,0,0,0,2,0,0,0,0,0
4,369,162,148,156,380,285,338,474,222,313,...,285,302,369,341,271,442,614,518,338,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,247,338,478,366,478,361,375,250,375,171,...,179,180,195,308,406,351,128,169,208,1
264,62,44,23,37,168,128,47,23,8,19,...,162,126,128,214,162,128,164,94,96,1
265,5,0,0,145,237,174,193,229,201,216,...,100,82,84,88,166,217,152,163,194,1
266,189,155,159,160,265,162,133,160,154,165,...,202,339,332,178,130,192,199,146,271,1
267,82,81,396,555,322,260,468,391,175,271,...,310,163,294,155,77,61,79,84,94,1