In [9]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fire/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

In [10]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [11]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='CANNY')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [12]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [13]:
x = [0] * 126
y =[1]*142
z=x+y

In [14]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    71400 66300 80070 78285 63240 42840 60180 6706...      0
1    94095 80325 68085 54570 60435 84150 45645 7573...      0
2    234855 210885 196095 204000 186150 229500 2070...      0
3    85680 87210 147645 160140 168555 170850 169830...      0
4    279735 264435 230520 238935 232560 235620 2850...      0
..                                                 ...    ...
263  290190 289170 270555 358275 337365 467925 3429...      1
264  31620 67065 19635 37995 237660 82620 113220 26...      1
265  2040 510 510 177225 196605 232560 174420 14101...      1
266  164220 149685 233070 214710 396015 175185 1491...      1
267  68085 47175 102765 158610 172890 156570 196095...      1

[268 rows x 2 columns]

In [15]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fire/CDI_Based/Intensity/CSV/Canny_With_Filter.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,71400,66300,80070,78285,63240,42840,60180,67065,79050,50235,...,60435,67830,86445,133365,100470,66555,44370,66555,88485,0
1,94095,80325,68085,54570,60435,84150,45645,75735,55080,56865,...,112965,89760,71655,110160,162180,132345,118320,135915,112965,0
2,234855,210885,196095,204000,186150,229500,207060,220575,183855,216240,...,217005,194310,198390,253980,242505,223380,201450,172890,209100,0
3,85680,87210,147645,160140,168555,170850,169830,151980,142035,159375,...,0,0,0,0,510,0,0,0,0,0
4,279735,264435,230520,238935,232560,235620,285090,254235,224910,203745,...,314925,263160,197115,188190,162945,186150,240210,205020,231285,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,290190,289170,270555,358275,337365,467925,342975,371790,457215,137700,...,173145,217515,267750,273870,253980,233580,208590,157845,211905,1
264,31620,67065,19635,37995,237660,82620,113220,26010,9945,8415,...,183345,167535,159630,136170,145860,109905,150450,150450,103020,1
265,2040,510,510,177225,196605,232560,174420,141015,143820,202470,...,96135,83385,69105,76500,107610,116025,126225,135915,161415,1
266,164220,149685,233070,214710,396015,175185,149175,191250,321810,184110,...,366690,210885,196605,122655,86190,159120,186150,174420,150195,1
267,68085,47175,102765,158610,172890,156570,196095,220830,201960,235875,...,145860,178245,145095,98430,122145,107610,108885,117810,167535,1