In [2]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit
from image_preprocessing import cdi_process,calc_entropy,edge_process
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fire/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

In [3]:
video=os.listdir(negative_os)

Euler_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            euler=edge_process.Edges_lib.Euler_Num(cdi)
            in_list.append(euler)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Euler_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:
video=os.listdir(positive_os)

P_Euler_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start)
            
            euler=edge_process.Edges_lib.Euler_Num(cdi)
            in_list.append(euler)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Euler_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [13]:

Combine_Euler=Euler_list+P_Euler_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Euler)):
#     Combine_Euler[i] = ((min_max_scaler.fit_transform(np.array(Combine_Euler[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Euler:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [14]:
x = [0] * 126
y =[1]*142
z=x+y

In [15]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    41 41 58 75 79 88 84 73 72 64 65 39 79 67 65 7...      0
1    30 71 63 58 65 66 74 59 68 63 51 31 75 64 58 4...      0
2    4 7 12 7 3 8 7 9 8 1 2 2 1 2 3 7 6 5 3 7 4 3 1...      0
3    32 27 16 11 22 15 13 26 29 17 18 12 12 12 41 8...      0
4    42 74 51 38 50 58 53 39 30 54 7 46 49 53 37 29...      0
..                                                 ...    ...
263  2 11 8 1 9 12 7 8 7 4 2 1 3 1 4 6 7 5 7 10 10 ...      1
264  7 20 6 5 2 1 7 7 14 19 14 6 6 1 4 9 1 3 2 3 2 ...      1
265  7 3 4 3 1 1 1 2 1 6 2 9 20 19 6 8 7 4 14 27 48...      1
266  1 2 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ...      1
267  32 20 12 6 10 14 15 8 10 15 3 10 7 14 13 17 19...      1

[268 rows x 2 columns]

In [16]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fire/CDI_based/Intensity/CSV/Euler_Num.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,41,41,58,75,79,88,84,73,72,64,...,83,84,73,23,46,63,64,58,71,0
1,30,71,63,58,65,66,74,59,68,63,...,39,64,69,51,26,72,72,72,61,0
2,4,7,12,7,3,8,7,9,8,1,...,7,4,3,1,3,3,11,3,1,0
3,32,27,16,11,22,15,13,26,29,17,...,0,0,0,0,11,6,1,1,1,0
4,42,74,51,38,50,58,53,39,30,54,...,12,29,23,4,42,38,27,67,39,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,2,11,8,1,9,12,7,8,7,4,...,10,10,7,8,8,6,7,9,6,1
264,7,20,6,5,2,1,7,7,14,19,...,3,2,5,4,2,3,3,8,14,1
265,7,3,4,3,1,1,1,2,1,6,...,27,48,18,26,5,10,3,3,6,1
266,1,2,1,1,1,2,2,1,1,1,...,1,1,1,1,1,1,1,1,1,1
267,32,20,12,6,10,14,15,8,10,15,...,20,13,11,16,12,15,15,17,6,1