In [1]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fire/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Intensity\Preprocessing\image_preprocessing\cdi_process.ipynb
importing Jupyter notebook from C:\Users\jingy\Jupyter\Crime\Fire\CDI_Based\Intensity\Preprocessing\image_preprocessing\calc_entropy.ipynb

In [2]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='LAPLACIAN')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [3]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=27:
            cdi,frame=My_CDI.CDI(start,methods='LAPLACIAN')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [5]:
x = [0] * 126
y =[1]*142
z=x+y

In [6]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    27943 26408 22559 18108 17102 15183 14332 1416...      0
1    30312 23451 20106 19234 17926 18400 17148 1613...      0
2    77531 66756 59647 64312 61813 62535 60469 6193...      0
3    26680 27309 40980 49425 45119 53857 50425 4502...      0
4    56064 45208 39599 36118 44464 50862 47301 5297...      0
..                                                 ...    ...
263  54139 55930 53127 57674 56713 60389 53087 5573...      1
264  4265 8255 3805 5302 40923 27041 25840 19696 95...      1
265  588 418 274 34764 45962 49027 39559 37714 3652...      1
266  53595 56013 63826 74100 124477 60306 51368 657...      1
267  11965 10208 23994 36181 45805 43804 40782 4975...      1

[268 rows x 2 columns]

In [7]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fire/CDI_Based/Intensity/CSV/Laplacian_With_Filter.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,Class
0,27943,26408,22559,18108,17102,15183,14332,14169,13202,13563,...,22435,26996,36390,39710,33864,21874,20031,22820,26808,0
1,30312,23451,20106,19234,17926,18400,17148,16130,18957,19160,...,30023,26417,21939,29548,44325,34509,33264,35860,35270,0
2,77531,66756,59647,64312,61813,62535,60469,61938,60161,62613,...,63943,59684,61812,72820,74703,67797,62966,56331,61825,0
3,26680,27309,40980,49425,45119,53857,50425,45027,48562,56637,...,122,122,122,52,1167,770,148,169,167,0
4,56064,45208,39599,36118,44464,50862,47301,52978,45575,44989,...,69179,60453,53143,63653,41747,41075,57767,44265,43208,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,54139,55930,53127,57674,56713,60389,53087,55733,71691,43248,...,47641,49730,48151,42979,37330,37851,39794,29524,33937,1
264,4265,8255,3805,5302,40923,27041,25840,19696,9544,8009,...,35403,28828,27741,27748,25231,24741,28181,21949,17599,1
265,588,418,274,34764,45962,49027,39559,37714,36520,34793,...,24460,20622,13823,16896,30040,28225,36579,39588,42859,1
266,53595,56013,63826,74100,124477,60306,51368,65764,89564,61691,...,102656,84644,68221,48726,47876,60181,66964,68836,65977,1
267,11965,10208,23994,36181,45805,43804,40782,49754,41040,44500,...,32104,28350,27480,36682,28719,27991,28382,28314,36474,1