In [2]:
import Ipynb_importer
import cv2 as cv
import sys,os
import time
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from collections import Counter
from numba import jit

from image_preprocessing import cdi_process,calc_entropy
from sklearn.preprocessing import StandardScaler,MinMaxScaler

%matplotlib inline
sns.set_style('darkgrid')

Home_os='C:/Users/jingy/Jupyter/Crime/Fire/Dataset/video/'
negative_os=Home_os+'negative/'
positive_os=Home_os+'positive/'

In [3]:
video=os.listdir(negative_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
Intensity_list=[]
for i in video:
    start=0
    video_name=negative_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [4]:
video=os.listdir(positive_os)
#My_CDI=cdi_process.CDI_lib(cap,Threshold=True,mythold=[0,255])
P_Intensity_list=[]
for i in video:
    start=0
    video_name=positive_os+i
    cap = cv.VideoCapture(video_name)
    My_CDI=cdi_process.CDI_lib(cap,Threshold=False,mythold=[0,255])
    in_list=[]
    while 1:
        if start<=26:
            cdi,frame=My_CDI.CDI(start,methods='OPTICAL')
            Intensity=My_CDI.CDI_Intensity(cdi,Normalization=False)
            in_list.append(Intensity)
            cv.imshow('frame',frame)
            cv.imshow('cdi',cdi)
            k = cv.waitKey(1) 
            start+=1
            if k ==27:     
                break 
        else:
            break
    P_Intensity_list.append(in_list)
    cap.release()
cv.destroyAllWindows()

In [5]:

Combine_Intensity=Intensity_list+P_Intensity_list
# min_max_scaler =MinMaxScaler()
# for i in range(len(Combine_Intensity)):
#     Combine_Intensity[i] = ((min_max_scaler.fit_transform(np.array(Combine_Intensity[i]).reshape(-1,1)))).reshape(-1).tolist()
new_list=[]
for i in Combine_Intensity:
        str1 = ' '.join([str(x) for x in i])
        new_list.append(str1)

print(len(new_list))

268

In [6]:
x = [0] * 126
y =[1]*142
z=x+y

In [7]:
combine_dict={'intensity':new_list,'label':z}
df=pd.DataFrame(combine_dict)

display(df)
y=df['label'].values

                                             intensity  label
0    372.92203 362.6913 350.63812 210.8773 214.7508...      0
1    240.19547 240.12958 256.62112 252.72621 170.48...      0
2    1517.8735 1229.6251 1227.2352 1408.0652 1701.6...      0
3    2443.0737 3847.7566 10229.559 3523.6807 6001.0...      0
4    9062.741 11081.287 10685.924 8698.271 5733.898...      0
..                                                 ...    ...
263  24703.18 10529.967 7170.648 16003.615 17353.64...      1
264  3298.5679 1485.2087 1531.6362 23056.814 89351....      1
265  142.57343 149.19235 14441.8125 28102.324 12007...      1
266  8838.767 27726.596 20305.998 45738.504 36611.7...      1
267  1362.3179 3432.692 4695.8667 6898.2524 11023.1...      1

[268 rows x 2 columns]

In [8]:
data_df = df['intensity'].str.split(' ', expand=True)

data_df['Class'] =y
data_df.to_csv('C:/Users/jingy/Jupyter/Crime/Fire/CDI_Based/Intensity/CSV/Optical_Mag.csv')
display(data_df)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,Class
0,372.92203,362.6913,350.63812,210.8773,214.75081,164.38365,212.3516,251.4654,312.6156,205.60248,...,288.03723,410.0701,441.60355,379.8768,1398.7834,278.716,301.12616,239.11705,477.2661,0
1,240.19547,240.12958,256.62112,252.72621,170.48306,281.75586,174.03131,173.71799,255.81352,238.5696,...,435.28314,518.0449,914.143,449.55862,2467.9111,4137.2305,3146.771,2503.685,910.9932,0
2,1517.8735,1229.6251,1227.2352,1408.0652,1701.6107,1425.3519,1373.9668,1437.9149,1633.4954,1862.8259,...,1676.284,1532.1061,1503.2603,1570.2098,1742.7628,1926.927,1565.9733,1381.2252,1356.1907,0
3,2443.0737,3847.7566,10229.559,3523.6807,6001.053,8588.636,15606.876,9383.27,9314.141,4888.855,...,2.9655285,2.965872,2.965872,1.3545805,3908.442,161.7076,52.62399,2.9529881,3.2751338,0
4,9062.741,11081.287,10685.924,8698.271,5733.8984,8995.766,8062.0996,9380.41,5809.6294,5657.079,...,52994.87,59666.29,20668.38,10549.264,3290.1765,5431.465,9030.6875,10763.368,9192.955,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,24703.18,10529.967,7170.648,16003.615,17353.648,15548.207,10682.514,40535.824,114278.97,44923.434,...,11710.026,11704.487,9859.623,15381.029,8233.648,6524.2046,10379.617,8576.629,5150.418,1
264,3298.5679,1485.2087,1531.6362,23056.814,89351.97,23801.676,78610.445,23310.027,23148.64,13286.738,...,13592.53,8032.7056,8559.471,13853.692,12117.484,10047.815,10048.92,8023.141,5045.871,1
265,142.57343,149.19235,14441.8125,28102.324,12007.33,13305.759,18995.36,3942.528,3642.4514,3436.8596,...,3571.1235,4132.2764,2351.6658,2268.4426,4443.415,5769.0083,4667.779,4951.398,8649.076,1
266,8838.767,27726.596,20305.998,45738.504,36611.777,9760.23,10156.101,14908.927,33021.06,23952.771,...,121140.95,14662.49,11355.047,11260.518,7024.2285,5204.0024,7922.694,6405.315,64505.066,1
267,1362.3179,3432.692,4695.8667,6898.2524,11023.139,17943.27,14343.605,18915.57,13119.688,16002.315,...,4794.359,4611.1035,3215.7544,3561.279,5640.7627,4596.208,5800.657,5063.8213,7905.587,1